export const CONSTANTS = {
    VERSION: "v0.0.1",
    DB_VERSION_KEY: "db_version",
    DB_VERSION: "v0.0.6",
    MODEL_PRICING_KEY: "MODEL_PRICING_CONFIG",
    BILLING_CONFIG_KEY: "BILLING_CONFIG",
    SYSTEM_CONFIG_KEY: "SYSTEM_CONFIG",
}
